CREATE DATABASE IF NOT EXISTS `${DB_USER_NAME}_test`;
GRANT ALL PRIVILEGES ON `${DB_USER_NAME}\_%`.* TO '${DB_USER_NAME}'@'%';
GRANT ALL PRIVILEGES ON `${DB_USER_NAME}\_%`.* TO '${DB_USER_NAME}'@'localhost';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
FLUSH PRIVILEGES;
